### ISSUE TITLE
My data not display

### ISSUE THREAD

**Issue by kmal47** [cmglez10/ng-datatable#1]
Im having problem in display the data from my firebase realtime database. Can you help me?

Below are my app.component.ts

       
     
     @Component({
     selector: 'app-employee-list',
       templateUrl: './employee-list.component.html',
     styleUrls: ['./employee-list.component.css']
     })
     export class EmployeeListComponent implements OnInit {
      employeeList: Employee[];
      constructor(private employeeService: EmployeeService, private tostr: ToastrService,
       ) { }

      ngOnInit() {
        var x = this.employeeService.getData();
        x.snapshotChanges().subscribe(item => {
         this.employeeList = [];
         item.forEach(element => {
           var y = element.payload.toJSON();
        y["$key"] = element.key;
        this.employeeList.push(y as Employee);
       
          });
         });
     }

      onEdit(emp: Employee) {
        this.employeeService.selectedEmployee = Object.assign({}, emp);
      }

      onDelete(key: string) {
        if (confirm('Are you sure to delete this record ?') == true) {
          this.employeeService.deleteEmployee(key);
         this.tostr.warning("Deleted Successfully");
        }
      }

    }

below are my app.component.html

    <table class="table table-striped" [mfData]="employeeList" #mf="mfDataTable" 
    [mfRowsOnPage]="5">
      <thead>
      <tr>
          <th style="width: 20%">
            <mfDefaultSorter by="serialnumber">Serial Number</mfDefaultSorter>
          </th>
           <th style="width: 50%">
            Asset Description
          </th>
       </tr>
      </thead>
      <tbody>
      <tr *ngFor="let employee of mf.employeeList">
        <td>{{employee.serialnumber}}</td>
       <td>{{employee.detailspecification}}</td>
      </tr>
      </tbody>
      <tfoot>
      <tr>
         <td colspan="4">
          <mfBootstrapPaginator [rowsOnPageSet]="[5,10,25]"></mfBootstrapPaginator>
         </td>
       </tr>
       </tfoot>
      </table>

**Comment by cmglez10** [comment]
You have a little bug in your app.component.html

Please change the line:

` <tr *ngFor="let employee of mf.employeeList">`

by

` <tr *ngFor="let employee of mf.data">`

Object mf data always is in mf.data

Please try it and let me know the result

**Comment by kmal47** [comment]
haha,its worked!thanks bro.Working on it for three days.You saved my life.

**Comment by cmglez10** [comment]
Great!
