### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by PascalHonegger** [cmglez10/ng-datatable#2]
Let's start of by saying I love your fork and we use it in our project.
As angular 6 was released today I wanted to ask if there are any plans to update to angular 6. The main change should be rxjs 6, which mostly contains syntactic changes. If you want I would try to create a pull request this weekend.

**Comment by cmglez10** [comment]
I do not have too much time at this moment, but please, feel free to create the pull request and I'll accept it.
Thanks!

**Comment by cmglez10** [comment]
Pull request merged

**Comment by PascalHonegger** [comment]
@cmglez10 Any updates about releasing version 0.8?
