### ISSUE TITLE
ERROR in : There is no directive with "exportAs" set to "mfDataTable"

### ISSUE THREAD

**Issue by jayantsr83** [cmglez10/ng-datatable#7]
Tables is working fine but when i build app it shows me this error

ERROR in : There is no directive with "exportAs" set to "mfDataTable" (" New Package</a>
    <table class="table table-striped table-hover table-bordered" [mfData]="data" [ERROR ->]#mf="mfDataTable" [mfRowsOnPage]="">
        <thead>"): Can't bind to 'mfData' since it isn't a known property of 'table'. 
        ("a-plus"></i> Add New Package</a>
    <table class="table table-striped table-hover table-bordered" [ERROR ->][mfData]="data" #mf="mfDataTable" [mfRowsOnPage]="">
        <thead>"): Can't bind to 'mfRowsOnPage' since it isn't a known property of 'table'. ("    <table class="table table-striped table-hover table-bordered" [mfData]="data" #mf="mfDataTable" [ERROR ->][mfRowsOnPage]="">  <thead>"): 'mfDefaultSorter' is not a known element:
        1. If 'mfDefaultSorter' is an Angular component, then verify that it is part of this module.
        2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </th>
                <th class="text-center" style="width: 50%">
                    [ERROR ->]<mfDefaultSorter by="title">Package Name</mfDefaultSorter>
                </th>
                <th ")
        : 'mfDefaultSorter' is not a known element:
        1. If 'mfDefaultSorter' is an Angular component, then verify that it is part of this module.
        2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </th>
                <th class="text-center" style="width: 30%">
                    [ERROR ->]<mfDefaultSorter by="pprice">Package Price</mfDefaultSorter>
                </th><t")
        : Can't bind to 'rowsOnPageSet' since it isn't a known property of 'mfBootstrapPaginator'. ("
            <tr>
                <td colspan="4">
                    <mfBootstrapPaginator [ERROR ->][rowsOnPageSet]="[5,10,25]"></mfBootstrapPaginator>
                </td>
            </tr>"): 'mfBootstrapPaginator' is not a known element:
        1. If 'mfBootstrapPaginator' is an Angular component, then verify that it is part of this module.
        2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            <tr>
                <td colspan="4">
                    [ERROR ->]<mfBootstrapPaginator [rowsOnPageSet]="[5,10,25]"></mfBootstrapPaginator>
                </td>")src/app/listmasterproducts/listmasterproducts.module.ts(5,45): error TS2307: Cannot find module './listmasterproducts/component'.

**Comment by jayantsr83** [comment]
Well my problem has been solved after using this command
`npm run build`

i was using 

`npm build --prod`

**Comment by cmglez10** [comment]
Sorry about my non-existing support :(
