### ISSUE TITLE
hide [rowsOnPageSet]

### ISSUE THREAD

**Issue by Isidroca** [cmglez10/ng-datatable#8]
Hellooo

very simple, it would be nice to have an option to hide the page options, I currently use

.pagination.pull-right.float-sm-right{
  display: none;
}

great job, thank you

**Comment by cmglez10** [comment]
If you pass an empty array in rowsOnPageSet variable, page options will not be shown:

Example:
`<mfBootstrapPaginator [rowsOnPageSet]="[]"></mfBootstrapPaginator>`
